import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { buildApp, isPermanentUser } from '../src/app.js';
import { heuristic } from '../src/extract.js';

test('health endpoint identifies the standalone backend and returns security headers',async()=>{const app=await buildApp();const response=await app.inject({method:'GET',url:'/health'});assert.equal(response.statusCode,200);assert.deepEqual(response.json(),{ok:true,service:'vaada-backend'});assert.equal(response.headers['x-content-type-options'],'nosniff');assert.equal(response.headers['x-frame-options'],'SAMEORIGIN');await app.close()});
test('readiness endpoint reports missing production dependencies without exposing values',async()=>{const app=await buildApp();const response=await app.inject({method:'GET',url:'/ready'});assert.equal(response.statusCode,503);assert.deepEqual(response.json(),{ok:false,service:'vaada-backend',checks:{cors:false,supabase:false,ai:false,agent:false}});assert.doesNotMatch(response.body,/key|secret|https?:\/\//i);await app.close()});
test('public promises work without Supabase by using the reviewed seed',async()=>{const app=await buildApp();const response=await app.inject({method:'GET',url:'/v1/promises'});assert.equal(response.statusCode,200);assert.ok(response.json().commitments.length>=6);await app.close()});
test('AI extraction requires a permanent signed-in account',async()=>{const app=await buildApp();const response=await app.inject({method:'POST',url:'/v1/extract',payload:{},headers:{'content-type':'multipart/form-data; boundary=x'}});assert.equal(response.statusCode,401);await app.close()});
test('anonymous Supabase users are not permanent accounts',()=>{assert.equal(isPermanentUser({is_anonymous:true}),false);assert.equal(isPermanentUser({is_anonymous:false}),true);assert.equal(isPermanentUser(null),false)});
test('heuristic extraction preserves uncertainty and the website deadline contract',()=>{const draft=heuristic('https://example.gov.in/notice','The Department of Education announced new classrooms in Karnataka.');assert.equal(draft.state,'Karnataka');assert.equal(draft.deadlineStart,'');assert.equal(draft.deadlineEnd,'');assert.ok(draft.warnings.some(item=>item.includes('deadline')))});
test('uploads require an authenticated user',async()=>{const app=await buildApp();const response=await app.inject({method:'POST',url:'/v1/uploads/proof',payload:'',headers:{'content-type':'multipart/form-data; boundary=x'}});assert.equal(response.statusCode,401);await app.close()});
test('review endpoints never accept unauthenticated decisions',async()=>{const app=await buildApp();const response=await app.inject({method:'POST',url:'/v1/review/submissions',payload:{submissionId:'00000000-0000-4000-8000-000000000000',decision:'accepted',note:'verified'}});assert.equal(response.statusCode,403);await app.close()});
test('invalid deadline windows are rejected before storage',async()=>{const app=await buildApp();const response=await app.inject({method:'POST',url:'/v1/submissions',headers:{authorization:'Bearer test'},payload:{submissionKind:'promise',title:'A valid public title',promiseText:'A sufficiently long exact promise statement.',sourceUrl:'https://example.gov.in/source',promisedOn:'2026-08-01',deadlineStart:'2026-08-03',deadlineEnd:'2026-08-02',deadlineLabel:'within two days',state:'Karnataka',district:'Bengaluru',category:'Governance',accountableOffice:'Public office',submitAnonymously:true,confidence:{},warnings:[]}});assert.equal(response.statusCode,400);assert.match(response.json().error,/end must be on or after/i);await app.close()});
test('database schema protects identity, review and private media',async()=>{const schema=await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8');assert.match(schema,/enable row level security/g);assert.match(schema,/anonymous_hides_identity/);assert.match(schema,/is_anonymous/);assert.match(schema,/create table public\.media_assets/);assert.match(schema,/sha256/);assert.match(schema,/reviewer access required/);assert.match(schema,/proof-media','proof-media',false/);assert.doesNotMatch(schema,/create policy "users upload own proof"/);assert.match(schema,/deadline_start/)});
