import OpenAI from 'openai';
import { zodTextFormat } from 'openai/helpers/zod';
import { z } from 'zod';
import { config } from './config.js';
import type { ExtractedDraft } from './types.js';

const DraftSchema=z.object({title:z.string(),promiseText:z.string(),promisedOn:z.string(),deadlineStart:z.string(),deadlineEnd:z.string(),deadlineLabel:z.string(),state:z.string(),district:z.string(),category:z.string(),accountableOffice:z.string(),confidence:z.record(z.string(),z.number().min(0).max(1)),warnings:z.array(z.string())});
const states=['Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'];
const categories:Record<string,string[]>={Education:['school','student','classroom','college','teacher'],Water:['water','pipeline','tap','irrigation'],Health:['hospital','clinic','health','bed','doctor'],Infrastructure:['road','bridge','rail','highway','building'],Jobs:['job','employment','apprentice','skill'],Transport:['bus','metro','transport','railway','airport'],Agriculture:['farmer','agriculture','crop','mandi'],Housing:['housing','homes','houses','resettlement']};
const privateHost=/^(localhost|127\.|0\.0\.0\.0|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|\[?::1\]?$)/i;

function publicHttpsUrl(value:string,base?:URL){const url=new URL(value,base);if(url.protocol!=='https:'||privateHost.test(url.hostname))throw new Error('Only public HTTPS sources can be read.');return url}
export async function fetchPublicSourceText(value:string){let url=publicHttpsUrl(value);let response:Response|undefined;for(let hop=0;hop<4;hop++){response=await fetch(url,{redirect:'manual',headers:{'user-agent':'VaadaSourceReviewer/1.0'},signal:AbortSignal.timeout(8000)});if(response.status<300||response.status>=400)break;const location=response.headers.get('location');if(!location)throw new Error('The source redirect was incomplete.');url=publicHttpsUrl(location,url)}if(!response||response.status>=300&&response.status<400)throw new Error('The source redirected too many times.');if(!response.ok)throw new Error(`Source returned ${response.status}. Upload a screenshot or paste the text instead.`);const contentType=response.headers.get('content-type')??'';if(!/(text|json|xml|html)/i.test(contentType))throw new Error('This source is not readable text. Upload the document instead.');const text=(await response.text()).slice(0,200000);return text.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,30000)}

export function heuristic(sourceUrl:string,rawText:string):ExtractedDraft{const clean=rawText.replace(/\s+/g,' ').trim();const lower=clean.toLowerCase();const state=states.find(name=>lower.includes(name.toLowerCase()))??'';const category=Object.entries(categories).find(([,words])=>words.some(word=>lower.includes(word)))?.[0]??'Governance';const date=clean.match(/\b(20\d{2}-\d{2}-\d{2}|\d{1,2}\s+[A-Za-z]+\s+20\d{2})\b/)?.[1]??'';const deadline=clean.match(/(?:by|before|within)\s+([^.;]{3,60})/i)?.[0]??'';const office=clean.match(/\b((?:Department|Ministry|Directorate|Municipal Corporation|Office)\s+of\s+[A-Z][A-Za-z& ,'-]{2,100})/)?.[1]??'';return{title:clean.split(/[.!?]/)[0]?.slice(0,140)||'Public promise awaiting a clear title',promiseText:clean,sourceUrl,promisedOn:/^20\d{2}-\d{2}-\d{2}$/.test(date)?date:'',deadlineStart:'',deadlineEnd:'',deadlineLabel:deadline,state,district:'',category,accountableOffice:office,confidence:{title:clean?.82:.2,state:state?.86:.18,category:.68,date:date?.76:.12,deadline:deadline?.72:.12,office:office?.72:.12},warnings:[...(!state?['State was not clear in the supplied source.']:[]),...(!date?['Promise date needs confirmation.']:[]),...(!deadline?['No stated deadline was detected. Do not invent one.']:[])]}}

export async function extractWithAgent(input:{sourceUrl:string;rawText:string;file?:{buffer:Buffer;mimeType:string;name:string}}):Promise<{draft:ExtractedDraft;mode:'ai'|'heuristic'}>{if(!config.openaiKey){if(input.file&&!input.rawText)throw new Error('Image/PDF reading needs OPENAI_API_KEY.');return{draft:heuristic(input.sourceUrl,input.rawText),mode:'heuristic'}}const content:Array<Record<string,unknown>>=[{type:'input_text',text:`Extract one concrete public promise from the supplied source. Preserve exact facts. Use empty strings for absent facts. Never infer truth or completion. Source URL: ${input.sourceUrl||'none'}\n\nSource text:\n${input.rawText||'Inspect the attached file.'}`}];if(input.file){const base64=input.file.buffer.toString('base64');if(input.file.mimeType.startsWith('image/'))content.push({type:'input_image',detail:'high',image_url:`data:${input.file.mimeType};base64,${base64}`});else content.push({type:'input_file',filename:input.file.name,file_data:`data:application/pdf;base64,${base64}`})}const client=new OpenAI({apiKey:config.openaiKey});const response=await client.responses.parse({model:config.openaiModel,input:[{role:'user',content}] as never,text:{format:zodTextFormat(DraftSchema,'vaada_promise_draft')}});if(!response.output_parsed)throw new Error('The extraction agent could not create a safe draft.');return{draft:{...response.output_parsed,sourceUrl:input.sourceUrl},mode:'ai'}}
